### ISSUE TITLE
Not Working on django > 3.0

### ISSUE THREAD

**Issue by jindalAnuj** [sandino/django-trumbowyg#10]
There is a six package issue.
throughing error

```
from trumbowyg.utils import slugify
  File "/Users/anuj/.local/share/virtualenvs/awesome_opensource-8yqixrIL/lib/python3.7/site-packages/trumbowyg/utils.py", line 2, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/Users/anuj/.local/share/virtualenvs/awesome_opensource-8yqixrIL/lib/python3.7/site-packages/django/utils/__init__.py)
```

**Comment by jindalAnuj** [comment]
Is this project is alive?

**Comment by sandino** [comment]
> There is a six package issue.
> throughing error
> 
> ```
> from trumbowyg.utils import slugify
>   File "/Users/anuj/.local/share/virtualenvs/awesome_opensource-8yqixrIL/lib/python3.7/site-packages/trumbowyg/utils.py", line 2, in <module>
>     from django.utils import six
> ImportError: cannot import name 'six' from 'django.utils' (/Users/anuj/.local/share/virtualenvs/awesome_opensource-8yqixrIL/lib/python3.7/site-packages/django/utils/__init__.py)
> ```

Hi,

Currently I have not enough time to fix this issue, but a PR would be very appreciated.

**Comment by jindalAnuj** [comment]
Yes i know that six is required directly instead of django utils.
I have used the package by downloading it as of now but will submit a pr for the same.If you don't mind you can add me as maintainer in this package.

Sent from Yahoo Mail on Android 
 
  On Sat, 19 Sep 2020 at 11:04 pm, sandino<notifications@github.com> wrote:   



There is a six package issue.
throughing error
from trumbowyg.utils import slugify
  File "/Users/anuj/.local/share/virtualenvs/awesome_opensource-8yqixrIL/lib/python3.7/site-packages/trumbowyg/utils.py", line 2, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/Users/anuj/.local/share/virtualenvs/awesome_opensource-8yqixrIL/lib/python3.7/site-packages/django/utils/__init__.py)


Hi,

Currently I have not enough time to fix this issue, but a PR would be very appreciated.

**Comment by jindalAnuj** [comment]
@sandino please merge this pull

**Comment by edvm** [comment]
Hit this same bug, unfortunately this PR isn't still merged :(
